repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-merge-conflict
  - id: debug-statements

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.0
  hooks:
  - id: terraform_fmt
    args:
    - --args=-no-color
    - --args=-diff
    - --args=-write=true
  - id: terraform_validate
  - id: terraform_docs
    args:
    - --args=--sort-by-required
    - --args=--sort-inputs-by-required
  - id: terraform_tflint
    args:
    - --args=--fix
  - id: terraform_checkov
    args:
    - --args=--skip-check=CKV_AWS_130
    - --args=--skip-check=CKV_AWS_126

- repo: https://github.com/terraform-linters/tflint
  rev: v0.47.0
  hooks:
  - id: tflint
    args:
    - --fix

- repo: local
  hooks:
  - id: terraform-validate
    name: terraform validate
    entry: terraform validate
    language: system
    pass_filenames: false
    always_run: true
    working_dir: test/

  - id: terraform-plan
    name: terraform plan
    entry: terraform plan -detailed-exitcode
    language: system
    pass_filenames: false
    always_run: true
    working_dir: test/
